### ISSUE TITLE
Single vs multiple app mode in develop branch

### ISSUE THREAD

**Issue by zferdana** [CoastalResilienceNetwork/GeositeFramework#1046] opened 2017-12-12 01:08 UTC
Casey - just want to make sure the develop branch can do both single and multiple app mode. I just tried --framework-branch=develop and got this:

![screen shot 2017-12-11 at 4 59 14 pm](https://user-images.githubusercontent.com/5605392/33862035-9d425900-de95-11e7-866d-d215677d7972.png)

I had to deploy the master framework in order to produce the dev oceanwealth region. I suspect we will need both modes working well on the develop branch to test both the super app in Hawaii as well as the in-app print (Jacob will test on dev oceanwealth).

**Comment by caseycesari** [comment] 2017-12-12 14:21
@zferdana Hi Zach. The `develop` branch can do both single and multiple app mode. It is configured via the region.json. There is likely something else causing the above problem.

Can you provide the full build command you ran so that I can try and reproduce this locally?
 Thanks.

**Comment by zferdana** [comment] 2017-12-21 20:01
Sure - I didn't change anything to region.json since I was building our traditional, multiple plugin framework mode.

build.py oceanwealth-region --prod --framework-branch=develop --region-branch=development

**Comment by caseycesari** [comment] 2017-12-22 17:54
@zferdana Can you try running the command again? I was able to reproduce the issue you were experiencing. I then merged https://github.com/CoastalResilienceNetwork/regional-planning/pull/95 into master for regional planning (this is related to https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/1043), tried the build command again, and the site worked.

Thanks.

**Comment by matts5517** [comment] 2018-01-03 19:31
Hey, I am also getting the same problem as above when building in Develop
my code: 
build.py wisconsin-region FreshwaterNetwork --dev --framework-branch=develop --region-branch=development.

I want to use the legend single column functionality which i think is only under the develop branch for now?

Thanks,
Matt

My console:

![screen shot 2018-01-03 at 12 30 22 pm](https://user-images.githubusercontent.com/19394069/34536312-f8189648-f081-11e7-8ccf-6c22dd8d5c72.png)

**Comment by caseycesari** [comment] 2018-01-03 20:18
Hi @matts5517,

I believe the error you reported is being caused by the regional-planning plugin, which is pinned at an old commit in the Wisconsin region. Take a look at https://github.com/FreshwaterNetwork/wisconsin-region/blob/b2e6e7fc5235cc959218e02dcde95904aaff3176/plugins.json#L6. That commit is from early 2017. If you update the `version` attribute to the latest commit, or drop the `version` attribute entirely, you'll get the latest version of `regional-planning`, which should fix this issue.

**Comment by matts5517** [comment] 2018-01-03 20:23
Thanks, that fixed the issue, sorry about that.

-Matt

**Comment by ajrobbins** [comment] 2018-01-11 14:27
This issue was resolved by using the latest version of regional-planning. Closing.

**Closed** 2018-01-11 21:05 UTC
Labels: tested/verified
