### ISSUE TITLE
Implement Launchpad

### ISSUE THREAD

**Issue by ajrobbins** [CoastalResilienceNetwork/GeositeFramework#736] opened 2016-11-16 20:44 UTC
The Launchpad currently appears as a "Getting Started" modal when a user reaches the site. Implement Launchpad as shown in these wireframes: https://marvelapp.com/19e970f/screen/16634903

With the following modifications:
- Rename "Launchpad" to "Get Started"
- If the plugin description is greater than a given height it is truncated with a View more link to expand the rest of the text.

**Comment by mmcfarland** [comment] 2016-11-17 18:52
Here's some detail on what that screenshot shows:

* The launchpad as is can be removed.
* The new launchpad looks like a plugin and behaves like one except for it's closing behavior.  Unlike plugins, it will never be "active" when it is not displayed and there is no explicit close `X`.
* The main title and main description are to be provided in the launchpad config (`region.json`)
* The plugin/apps listed in the Explore section are also configured, it's not a straight reproduction of the plugin list.  The configuration should accept a title, description and somehow reference the plugin so that it can be activated by the `Go` button.  I think `plugin_name` ('regional-planning`), similar to a region's `plugin.json` file would allow us to look up the right plugin to activate - but determine what kind of marker is best.

Sponsor section is handled by #

**Comment by ajrobbins** [comment] 2016-11-21 19:16
To clarify: The screen linked above (screen 1) is what we're implementing. We are not implementing screen 2 (https://marvelapp.com/19e970f/screen/16634905)

**Closed** 2016-12-01 20:33 UTC
