### ISSUE TITLE
Infographic continue button should fire resize event for plugin

### ISSUE THREAD

**Issue by mmcfarland** [CoastalResilienceNetwork/GeositeFramework#364] opened 2015-03-23 13:21 UTC
From George:

In several of my apps I create form elements that are placed out and sized in Javascript rather than just in CSS (they respond to the resize event to update).  One problem is that some of these elements, when they are drawn will not draw correctly when their parent element is hidden (display: none).  This happens when an infographic is given for a plugin (the main plugin panel is hidden until they click continue.  

I've coded up a hack that works around this (query for the continue button on the infographic and attach an even to it).  However, it would be nice to have this included in the framework code though so I would not have to include it in each plugin that gets built.

Really I think just firing resize when ever the main display (plugin-container-inner) is unhidden would work best, and likely is only a line or two of code.

**Comment by caseypt** [comment] 2015-03-30 13:56
Duplicate of #387

**Closed by caseypt** 2015-03-30 13:56 UTC
