### ISSUE TITLE
Super App Mode jQuery Issue

### ISSUE THREAD

**Issue by cschneebeck** [CoastalResilienceNetwork/GeositeFramework#1115] opened 2018-09-19 16:52 UTC
When building a region in single app mode, if the app doesn't import jQuery the site will build but will error out in the browser siting that an ESRI file can't bring in jQuery.

To test this, comment out lines 2-4 in main.js in the [ecological-effects-slc](https://github.com/CoastalResilienceNetwork/ecological-effects-slc/blob/development/main.js) repo. 
![screen shot 2018-09-19 at 10 51 35 am](https://user-images.githubusercontent.com/11446978/45768417-0848b180-bbfa-11e8-8337-ba34adec4452.png)

Now build the hawaii-region in dev.

The browser will then throw the following error. Bringing back lines 2-4 fixes this.
![screen shot 2018-09-19 at 10 49 21 am](https://user-images.githubusercontent.com/11446978/45768324-d1729b80-bbf9-11e8-955f-9608c6b18336.png)

**Comment by caseycesari** [comment] 2018-09-26 20:04
Hi @cschneebeck. I remember seeing this on our call, but I'm having trouble reproducing it now. Could you share the build command in full that you use to generate the hawaii-region? Just want to make sure I'm doing everything the same that you are. Thanks.

**Comment by cschneebeck** [comment] 2018-09-26 22:18
Here you go: hawaii-region --dev --framework-branch=master --region-branch=master

Cheers,
Casey Schneebeck
Web Developer | The Nature Conservancy - North America Region | 415-722-9768



On Wed, Sep 26, 2018 at 3:04 PM -0500, "Casey Cesari" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @cschneebeck<https://github.com/cschneebeck>. I remember seeing this on our call, but I'm having trouble reproducing it now. Could you share the build command in full that you use to generate the hawaii-region? Just want to make sure I'm doing everything the same that you are. Thanks.

**Comment by caseycesari** [comment] 2018-09-27 14:17
Thanks @cschneebeck. I ran that command and checked out the built site. I'm not able to reproduce the error anymore. Can you double-check that it's still happening for you? We recently pushed a bunch of fixes to `master`, so it's possible that it's been fixed.

**Comment by cschneebeck** [comment] 2018-09-27 19:50
Cool. I'm traveling this week but will check it out on Monday.

Cheers,
Casey Schneebeck
Web Developer | The Nature Conservancy - North America Region | 415-722-9768



On Thu, Sep 27, 2018 at 9:18 AM -0500, "Casey Cesari" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @cschneebeck<https://github.com/cschneebeck>. I ran that command and checked out the built site. I'm not able to reproduce the error anymore. Can you double-check that it's still happening for you? We recently pushed a bunch of fixes to master, so it's possible that it's been fixed.

**Comment by caseycesari** [comment] 2018-12-12 18:57
Example site: http://nstdevsites.s3-website-us-west-1.amazonaws.com/hawaii/

**Comment by caseycesari** [comment] 2018-12-17 16:47
Hi @cschneebeck, I looked into this issue this morning and figured out what's going. The reason that the plugin, with the jQuery import commented out, works fine in normal mode but fails in single-plugin mode is because the plugin is able to use versions of jQuery that are brought in by the plugins that come with the framework (launchpad and identify point). In single-plugin mode, since the ecological-effects-slc plugin is the only plugin in the framework, it fails to load because jQuery isn't available. 

I looked into the history of the framework a bit, and I believe the reason that plugins don't use the framework version of jQuery is to provide more flexibility for plugin developers. The framework is stuck on jQuery 1.x for now as there are some non-breaking changes we have to make to update the framework to support jQuery 2.x. Plugins, however, are free to use jQuery 2.x.

I think the quickest fix for this now is to remove the comments in this plugin and allow it to import jQuery.

In the future we could evaluate if it makes more sense to have the plugins use the framework version of jQuery as a fallback.

Does that make sense?

**Comment by caseycesari** [comment] 2018-12-17 18:43
@cschneebeck I think the other issue should be fixed by #1156. This fixes the errors related in the console to the logger. Is there another issue I'm missing?

**Comment by cschneebeck** [comment] 2018-12-17 18:48
I'm referring to the behavior we see here: 
http://nstdevsites.s3-website-us-west-1.amazonaws.com/hawaii/
If this was updated since our call I will try to test it later today.

**Comment by caseycesari** [comment] 2018-12-17 19:23
![image](https://user-images.githubusercontent.com/1042475/50109967-2462eb80-0207-11e9-9bf4-3b6d8030b964.png)

^ That issue is fixed by including jQuery in the EES `main.js` file since there isn't a framework-wide jQuery that plugins can inherit.

![image](https://user-images.githubusercontent.com/1042475/50110041-49eff500-0207-11e9-9fa0-45d78c3f22a7.png)

^ That issue is fixed by #1156, though it hasn't been merged into `feature/task-1` yet, so you may want to hold off on testing.

**Comment by cschneebeck** [comment] 2018-12-17 19:24
Cool. Let me know when it's in there and I'll check it out.

**Comment by caseycesari** [comment] 2018-12-19 13:41
@cschneebeck Can you rebuild hawaii region on the `feature/task-1` branch? The logger fix has been merged.

**Comment by cschneebeck** [comment] 2018-12-19 17:13
It was rebuilt last night to https://maps2.coastalresilience.org/hawaii-secure/ and the recent merge appears to have fixed the problem. Thanks!

Cheers,
Casey Schneebeck
Web Developer | The Nature Conservancy - North America Region | 415-722-9768

**Comment by caseycesari** [comment] 2018-12-19 17:14
Great!

**Closed** 2018-12-27 20:33 UTC
Labels: Task 4, bug, tested/verified
