### ISSUE TITLE
Export map button disabled

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#591] opened 2016-03-02 14:56 UTC
Is this a regression defect?

**Comment by mmcfarland** [comment] 2016-03-14 15:31
Is this still happening?  If so, it sounds like a regression.

**Comment by caseypt** [comment] 2016-04-06 12:24
I just tested out the map export button in the new layer selector and I was able to generate a PDF.

**Comment by mmcfarland** [comment] 2016-04-06 13:34
Also am not able to reproduce.  Closing unless it's reported again.

**Closed by mmcfarland** 2016-04-06 13:34 UTC
Labels: bug, layer selector v2
