### ISSUE TITLE
Blank map after failed map export

### ISSUE THREAD

**Issue by kdeloach** [CoastalResilienceNetwork/GeositeFramework#766] opened 2016-12-08 18:20 UTC
I received a CORS error when trying to export the map with one of the Hurricane Sandy layers selected in the regional planning plugin. When I closed the export map dialog, the map was blank.

![image](https://cloud.githubusercontent.com/assets/43062/21021899/9b91cd44-bd48-11e6-8975-d4375a9ee467.png)

To reproduce:

* Select one of the Hurricane Sandy layers in the regional planning plugin
* Export the map
* Close the export map dialog

**Comment by caseycesari** [comment] 2017-12-13 16:50
Unable to reproduce. Closing for now.

**Closed by caseycesari** 2017-12-13 16:50 UTC
Labels: bug, prototype-branch
