### ISSUE TITLE
Fix map plugin activation

### ISSUE THREAD

**Issue by caseypt** [CoastalResilienceNetwork/GeositeFramework#700] opened 2016-10-18 17:51 UTC
Clicking on this plugin doesn't appear to be activating them.

**Comment by ajrobbins** [comment] 2016-10-20 15:47
Closing in favor of https://github.com/CoastalResilienceNetwork/GeositeFramework/issues/688

**Comment by kdeloach** [comment] 2016-10-20 17:18
I'd like to reopen this issue because it's still happening for me and it doesn't seem caused by #688 (nor does it seem within the scope of #688 to fix).

**Closed** 2016-11-03 20:31 UTC
Labels: prototype-branch
