### ISSUE TITLE
Drop shadow covers small sidebar

### ISSUE THREAD

**Issue by lesserj** [CoastalResilienceNetwork/GeositeFramework#958] opened 2017-04-24 18:00 UTC
When opening up an app with the minimized version of the toolbar, the toolbar turns white and the apps are not visible.

![image](https://cloud.githubusercontent.com/assets/2304500/25351227/de84c912-28dc-11e7-95c7-595f52286c69.png)

The offending css appears to be line 743 of main.css

.sidebar {
  box-shadow: 0px 0px 26px 0px rgba(51, 51, 51, 0.42);
  z-index: 2000;
}

Disabling the box-shadow css corrects the issue.  That does get rid of the box shadow in the app however.  The css needs to be tweaked to preserve the box shadow without covering the toolbar.

c.c. @zferdana @iKimbot

**Comment by lesserj** [comment] 2017-04-24 21:27
Here's a video of this occurring.  The rendering issue seems to be dependent on screensize.  It is not always consistent.  I think the safest thing for now is to disable the box-shadow until we can figure out what's going on exactly.

![sidebar-box-shadow](https://cloud.githubusercontent.com/assets/2304500/25359323/9e72854a-28f9-11e7-93bf-3c41f0ca369e.gif)

I've noticed this on both Protecting Water and Ocean Wealth.  I have not been able to reproduce in my local environment.

**Comment by lesserj** [comment] 2017-04-24 21:46
If I change the z-index value of the sidebar class from 2000 to 1, the dropshadow is preserved, but the issue is no longer present.  I haven't been able to figure out why (yet).

**Comment by lesserj** [comment] 2017-04-24 23:17
Seems to be some sort of overflow issue with the sidebar-nav header.  Very strange.

![header-overflow](https://cloud.githubusercontent.com/assets/2304500/25362525/4b2a8de6-2909-11e7-8df1-ad5a31e8823e.gif)

**Comment by kdeloach** [comment] 2017-04-24 23:47
We are unable to reproduce this error. Could you provide any more details on how to reproduce this? There are some other style errors in your screenshot which we don't see (ex. the "expand sidebar" button is misplaced). We should rule out anything specific to your system which could be causing this error.

**Comment by lesserj** [comment] 2017-04-25 14:32
@kdeloach This doesn't occur on my local dev environnent, but I can reproduce it on 2 separate servers, maps.oceanwealth.org and maps.protectingwater.org.  Here's where the plot thickens.  It only happens on high-density displays.  It happens on my macbook with retina display.  I also have a large desktop monitor on my Windows machine set at 3840x2160.  It occurs on the large monitor, but if I drag the window to my smaller monitor, it renders normally (I'm not using the browser full screen, it is windowed).  If I reduce the resolution of my large monitor down to 2560x1600, the site starts rendering normally again, and I can't get the bug to trigger.  So, this seems to just affect high-density displays.  Googling around for box-shadow and high resolution or retina display returns a lot of issues, although, I haven't found anything exactly like ours, yet.  A solution though is to use a linear gradient background rather that box-shadow (all though, that's just avoiding the issue rather than understanding it).  See here: http://hackingui.com/front-end/chrome-box-shadow-bug-that-crashed-our-site/

I think we are getting into weird browser bug rendering territory.

**Comment by lesserj** [comment] 2017-04-25 14:39
Although, weirdly enough, this does not happen on my local environment, just the versions on the server.  I have no idea what is different between the two, or why it would matter.

**Comment by lesserj** [comment] 2017-04-25 14:59
To specifically address your concern about different css on my version, the misplaced expand button is only misplaced because I had been playing with the styles in dev tools trying to trigger/untrigger the error.  I should have refreshed before taking the video.  The action I perform above, changing the font-size, or toggling the box-shadow property is all that is needed to get the app to render correctly/incorrectly after a refresh.

**Comment by ajrobbins** [comment] 2017-04-25 17:08
Hi @lesserj, we've been attempting to reproduce this issue on a variety of high-resolution monitors. We were unable to reproduce it on:
- Retina screens on macbooks
- Large screen (3440 x 1440) Chrome on Mac
- Chrome on Windows 10

It's possible that it only applies to certain screen resolutions in Chrome on Windows. Since this is a pretty extreme edge case, we don't think it merits a framework fix at this time.

**Comment by lesserj** [comment] 2017-04-25 17:36
@ajrobbins Thanks for looking into it.  I've been able to reproduce on both my macbook and my windows PC.  You're correct that this only seems to impact Chrome.  I've been unable to reproduce in other browsers.  I've seen the issue occur in both Chrome 56.x and 57.x.  This was reported independently to me from our project manager in another office, so this is affecting more people than just me.  We've passed this off to a another developer to see if he can reproduce and has any ideas to the cause.  The strangest thing to me is that this only occurs on the TNC dev servers.  It does not occur when running off my local server, even though they are supposedly delivering the same code.  I'll let you know what more information we find.  When this bug does occur, it is serious enough to prevent use of the app, so we will continue to look for a fix.

**Comment by kdeloach** [comment] 2017-04-25 19:25
Thanks for the extra details. Unfortunately, since we can't reproduce this issue, we won't be able to verify that any changes we make will fix it. Could there be something specific to your environment which causes this? 

We attempted to reproduce this issue on various operating systems at different resolutions but the result was the same each time. One curious detail I noticed from your screen capture is that the scaling characteristics of the nav bar title are different compared to other browsers I tested (see screenshot). The fact that this only happens on dev servers is also suspicious.

Please keep us updated if you're able to figure out the root cause of this issue.

Windows 10 Chrome 57 1920x990
![image](https://cloud.githubusercontent.com/assets/43062/25403096/34fac020-29c9-11e7-9c75-58ab3bd620c3.png)

**Comment by caseycesari** [comment] 2017-08-08 18:21
We've been able to reproduce this on http://maps.coastalresilience.org/hawaii/ by activating the Ecosystem Effects of Sea Level Change plugin.

**Comment by caseycesari** [comment] 2017-08-24 14:13
@lesserj Just a heads up that we merged a fix (based off of your fix) into `master` yesterday. Thanks for your work on this. Let us know if it's still an issue.

**Closed** 2017-08-24 20:03 UTC
